isPublic: true
name: 'Public Schema'
scope:
  - 'sites.c6bfe418-2d2a-4ce7-876c-1f06f88a1ad9:read' # $DEFAULT_SITE_NAME
  - 'sections.1d3def5f-9f15-45a3-a3e4-1e3162007ebe:read' # Home
  - 'sections.1f3da7ed-2af0-40f7-96e4-6a943237d0aa:read' # Pages
