dateModified: 1757570944
email:
  fromEmail: craft@thasmo.email
  fromName: $APP_SYSTEM_NAME
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  storage:
    hasUrls: true
    name: Storage
    settings:
      path: $APP_FILES_PATH
    type: craft\fs\Local
    url: $APP_FILES_URL
meta:
  __names__:
    74f78f86-64ac-4d6c-aeef-f4b85077ed91: $APP_SYSTEM_NAME # $APP_SYSTEM_NAME
    c6bfe418-2d2a-4ce7-876c-1f06f88a1ad9: $DEFAULT_SITE_NAME # $DEFAULT_SITE_NAME
system:
  edition: solo
  live: true
  name: $APP_SYSTEM_NAME
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
