defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1b5b6229-0f99-4c8a-84be-03bda866ff34 # Page
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c6bfe418-2d2a-4ce7-876c-1f06f88a1ad9: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: pages
    uriFormat: __home__
type: single
