defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1b5b6229-0f99-4c8a-84be-03bda866ff34 # Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c6bfe418-2d2a-4ce7-876c-1f06f88a1ad9: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: sections/pages.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: b7bb328d-9f43-4fda-af50-0af8bef1b3ee
type: structure
